<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[The Method ActiTimeInvalidLogin got failed and screenshot has been taken]]>
    </line>
  </reporter-output>
  <suite started-at="2022-06-13T22:04:22 IST" name="Default suite" finished-at="2022-06-13T22:04:28 IST" duration-ms="5898">
    <groups>
    </groups>
    <test started-at="2022-06-13T22:04:22 IST" name="Default test" finished-at="2022-06-13T22:04:28 IST" duration-ms="5898">
      <class name="testpackage.TestActiTimeInvalidLogin">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testpackage.TestActiTimeInvalidLogin@be35cd9]" started-at="2022-06-13T22:04:22 IST" name="setUp" finished-at="2022-06-13T22:04:26 IST" duration-ms="4121" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="ActiTimeInvalidLogin()[pri:0, instance:testpackage.TestActiTimeInvalidLogin@be35cd9]" started-at="2022-06-13T22:04:26 IST" name="ActiTimeInvalidLogin" finished-at="2022-06-13T22:04:27 IST" duration-ms="1090" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.apache.poi.ss.usermodel.Cell.getStringCellValue()" because "cl" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Cell.getStringCellValue()" because "cl" is null
at generic.Flib.readExcelData(Flib.java:23)
at testpackage.TestActiTimeInvalidLogin.ActiTimeInvalidLogin(TestActiTimeInvalidLogin.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[The Method ActiTimeInvalidLogin got failed and screenshot has been taken]]>
            </line>
          </reporter-output>
        </test-method> <!-- ActiTimeInvalidLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testpackage.TestActiTimeInvalidLogin@be35cd9]" started-at="2022-06-13T22:04:28 IST" name="tearDown" finished-at="2022-06-13T22:04:28 IST" duration-ms="376" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testpackage.TestActiTimeInvalidLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
